services:

  price-list:
    image: anasortukov/price-list-ms:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    container_name: price-list

  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: price_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5455:5432"

volumes:
  postgres-data:
    driver: local